# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_id',
            field=models.IntegerField(default=0, verbose_name='权限等级'),
        ),
    ]
